let _metadata = createMetadata({
    // A LINK BETWEEN WORLDS
    "Boss Theme (Hyrule) - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Death Mountain - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Deeper into the Lost Woods - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Desert Palace - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Fortune Teller - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Hyrule at Peace - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Hyrule Hotfoot - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Irene - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Lorule Castle - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Meeting Princess Zelda - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Milk Bar - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Mother Maimai - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Overworld (Hyrule) - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Overworld (Lorule) - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Queen Oren - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Ravio's Shop - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Ravio's Theme - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Skull Woods - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Sneaking into the Dark Palace - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Staff Roll Credits - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "The Dark Palace - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Thieves Hideout - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Title Screen - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Treacherous Tower - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Turtle Rock - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Yuga Battle - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],
    "Yuga's Ballad - A Link Between Worlds": [2013, "Nintendo 3DS", "A Link Between Worlds"],



    // A LINK TO THE PAST
    "Battle with Ganon - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "Dank Dungeons - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "Dark World - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "Death Mountain - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "Epilogue ~ Beautiful Hyrule - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "File Select - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "Hyrule Castle - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "Princess Zelda's Rescue - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "Sanctuary Dungeon - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],
    "Seal of the Seven Maidens - A Link to the Past": [1991, "Super Nintendo", "A Link to the Past"],


  
    // BREATH OF THE WILD
    "A King's Request - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Abandoned North Mine - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Akkala Ancient Tech Lab - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Attack on Vah Medoh - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Attack on Vah Naboris - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Attack on Vah Rudania - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Attack on Vah Ruta - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Beast Ganon (Phase 1) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Beast Ganon (Phase 2) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Beast Ganon (Phase 3) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Blight Ganon - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Boss Defeated (Cutscene) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Calamity Ganon (Phase 1) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Calamity Ganon (Phase 2) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Cave - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Death Mountain - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Divine Beast Vah Medoh - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Divine Beast Vah Naboris - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Divine Beast Vah Rudania - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Divine Beast Vah Ruta - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Dragon - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Dungeon Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Field Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Flight Spot Trial - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Gerudo Canyon - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Gerudo Champion Urbosa's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Gerudo Town (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Gerudo Town (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Get Master Sword - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Goron Champion Daruk's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Goron City (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Goron City (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Great Fairy Fountain - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Guardian Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hateno Ancient Tech Lab - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hateno Village (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hateno Village (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Heat Test Minigame - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hinox Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Horse God Malanya's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "House - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hunting Minigame - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hyrule Castle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hyrule Castle Town - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hyrule Field (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Hyrule Field (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Impa's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Kakariko Village (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Kakariko Village (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Kara Kara Bazaar - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Kass's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Kilton's Monster Shop - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Korok Forest (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Korok Forest (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Lurelin Village (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Lurelin Village (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Lynel / Yiga Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Main Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Master Kohga Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Master Kohga's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Maze Forest (Lost Woods) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Molduga Battle (Phase 1) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Molduga Battle (Phase 2) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Mountain - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Omen of the Bloody Moon - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Parasailing Minigame - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Prince Sidon's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Riding Horse (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Riding Horse (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Rito Champion Revali's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Rito Village (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Rito Village (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Sheikah Tower - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Shieldsurfing Minigame - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Shrine Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Shrine Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Snow - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Stables - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Stationary Guardian Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Talus Battle - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Tarrey Town - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Temple of Time - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "The Divine Beasts Strike - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Volcano - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Water Side - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Yiga Assassin Base - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Zora Champion Mipha's Theme - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Zora's Domain (Day) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],
    "Zora's Domain (Night) - Breath of the Wild": [2017, "Nintendo Switch", "Breath of the Wild"],



    // FOUR SWORDS
    "Boss Battle - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Chamber of Insight - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Monster Battle - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Prologue - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Sea of Trees - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Talus Cave - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Title Theme - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Vaati's Palace - Four Swords": [2002, "Game Boy Advance", "Four Swords"],



    // FOUR SWORDS ADVENTURES
    "Boss Battle - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Chamber of Insight - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Monster Battle - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Prologue - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Sea of Trees - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Talus Cave - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Title Theme - Four Swords": [2002, "Game Boy Advance", "Four Swords"],
    "Vaati's Palace - Four Swords": [2002, "Game Boy Advance", "Four Swords"],



    // LINK'S AWAKENING (2019)
    "Animal Village - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Ballad of the Wind Fish (Commercial) - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Ballad of the Wind Fish (Instruments) - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Ballad of the Wind Fish (Marin) - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Ballad of the Wind Fish (Shore) - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Boss Battle - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Cave - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Chamber Dungeon (Edit Mode) - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Christine's House - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Color Dungeon - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Cucco House - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Dampe's House - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Dream Shrine - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Fairy Fountain - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Field - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "File Select - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Fishing Game - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Frog's Song of Soul - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Game Over - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Guardian Acorn - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "House by the Cove - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Inside a House - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Kanalet Castle - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Level 1: Tail Cave - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Level 2: Bottle Grotto - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Level 3: Key Cavern - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Level 4: Angler's Tunnel - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Level 5: Catfish's Maw - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Level 6: Face Shrine - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Level 7: Eagle's Tower - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Level 8: Turtle Rock - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Mabe Village - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Manbo's Mambo - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Mini Boss Battle - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Mr. Write's House - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Mysterious Forest - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Owl - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Passage - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Rapids Ride - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Rapids Ride (Time Attack) - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Rescue BowWow - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Richard's Villa - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Seashell Mansion - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Shadow Battle - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Shop - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Southern Face Shrine - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Tal Tal Heights - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Telephone Booth - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Title - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Trendy Game - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Turtle Rock Battle - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Waking Up At Tarin's House - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],
    "Wind Fish's Egg - Link's Awakening (2019)": [2019, "Nintendo Switch", "Link's Awakening (2019)"],



    // LINK'S AWAKENING DX
    "Animal Village - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Ballad of the Wind Fish (Instruments) - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Ballad of the Wind Fish (Shore) - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Boss Battle - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Cave - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Christine's House - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Color Dungeon - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Cucco House - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Dream Shrine - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Fairy Fountain - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Field - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "File Select - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Frog's Song of Soul - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Game Over - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Guardian Acorn - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "House by the Cove - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Inside a House - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Kanalet Castle - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Level 1: Tail Cave - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Level 2: Bottle Grotto - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Level 3: Key Cavern - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Level 4: Angler's Tunnel - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Level 5: Catfish's Maw - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Level 6: Face Shrine - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Level 7: Eagle's Tower - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Level 8: Turtle Rock - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Mabe Village - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Manbo's Mambo - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Mini Boss Battle - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Mr. Write's House - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Mysterious Forest - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Owl - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Passage - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Rapids Ride - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Rescue BowWow - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Richard's Villa - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Shadow Battle - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Shipwreck - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Shop - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Southern Face Shrine - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Tal Tal Heights - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Telephone Booth - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Title - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Trendy Game - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Turtle Rock Battle - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Waking Up At Tarin's House - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],
    "Wind Fish's Egg - Link's Awakening DX": [1998, "Game Boy Color", "Link's Awakening DX"],



    // MAJORA'S MASK
    "Astral Observatory - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Battle - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Boat Cruise - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Boss Battle - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Chase - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Clock Tower - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Clock Town, First Day - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Clock Town, Second Day - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Clock Town, Third Day - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Cremia's Wagon - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Deku Palace - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Elegy of Emptiness - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Final Hours - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Giants' Theme - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Goron Race - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Great Bay Coast - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Great Bay Temple - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Happy Mask Salesman's Theme - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Kamaro's Dance - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Keaton's Quiz - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Majora's Incarnation Battle - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Majora's Mask Battle - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Majora's Theme - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Majora's Wrath Battle - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Mayor's Meeting - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Milk Bar - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Music Box House - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "New Wave Bossa Nova - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Oath To Order - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Pirate Fortress - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Sonata Of Awakening - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Song Of Healing - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Southern Swamp - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Staff Roll Credits - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Stone Tower Temple - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Swordsman's School - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],
    "Title Theme - Majora's Mask": [2000, "Nintendo 64", "Majora's Mask"],



    // OCARINA OF TIME
    "Battle - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Bolero of fire - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Boss Battle - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Deku Tree - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Dodongo Battle - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Dodongo's Cavern - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Escape From Ganon's Castle - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Final Battle - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Forest Temple - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Ganon's Castle Bridge - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Ganon's Tower - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Ganondorf - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Ganondorf Battle - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Gerudo Valley - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Goron City - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Great Fairy's Fountain - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Horse race - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Hyrule Castle Courtyard - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Hyrule Field - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Ice Cavern - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Ingo - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Inside a House - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Inside Lord Jabu Jabu - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Inside the Great Deku Tree - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Kaepora Gaebora - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Kakariko Village - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Kokiri Forest - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Koume and Kotake - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Legend of Hyrule - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Lon Lon Ranch - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Lost Woods - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Market - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Middle Boss Battle - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Mini Game - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Minuet of the Forest - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Navi the fairy - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Nocturne of Shadow - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Potion Shop - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Prelude of Light - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Princess Zelda - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Requiem of Spirit - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Serenade of Water - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Shadow Temple - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Sheik - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Shooting Gallery - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Shop - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Spirit Temple - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Staff Roll Credits - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Temple of Time - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Water Temple - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Windmill Hut - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "You Got a Spirtual Stone ! - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Zelda - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],
    "Zora's Domain - Ocarina of Time": [1998, "Nintendo 64", "Ocarina of Time"],



    // PHANTOM HOURGLASS
    "Astrid's Theme - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "Bellum Battle - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "Dark King Ganon - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "Goron House - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "Linebeck's Theme - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "Phantom in Pursuit - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "Phantom Linebeck Battle - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "Prologue: Tetra and Her Handsome Pirates - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "The King of the Oceans - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],
    "Time Stopped - Phantom Hourglass": [2007, "Nintendo DS", "Phantom Hourglass"],



    // SKYWARD SWORD
    "Demon Lord, Ghirahim First Battle - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "A Sudden Crashlanding - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Ancient Cistern - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Ballad of the Goddess - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Ballad of the Goddess ~ Zelda Solo - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Bamboo Island - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Batreaux's Theme - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Battle - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Bazzar - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Bilocyte Battle - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Bucha's Theme - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Channel Intro - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Chasing Fi - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Crimson Loftwing - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Dance of the Goddess - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Din's Power - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Din's Silent Realm - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Eldin Volcano - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Eternal Gratitude/ Fi's Theme - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Exploring the Skies - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Faron Woods - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Farore's Courage - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Farore's Silent Realm - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "File Select - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Fire Sanctuary - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Floating Island - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Flooded Faron Woods - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Gaepora's Lament - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Ghirahim's Theme - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Goddess' Silent Realm - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Great Spirit Of The Skies, Levias - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Groose's Insolence - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Groose's Theme - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Grooseland - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Guardian Pursuit - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Inside a House - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Inside the Great Tree - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Knight Academy - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Koloktos ~ Moldarach Battle - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Lady Of The Sealed Grounds - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Lake Floria - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Lanayru Desert - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Lanayru Mining Facility - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Lanayru Sand Sea - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Leaping From The Clouds - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Link's Nightmare - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Loftwing Race - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Loftwing Training - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Magmanos - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Mogma Theme - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Nayru's Silent Realml - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Nayru's Wisdom - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Overture ~ Ballad of the Goddess - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Pirate Stronghold - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Pumpkin Harvest - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Romance in the Air - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Sandship (Exterior) - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Sandship (Interior) - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Sandship ~ Past - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Scaldera ~ Tentalus Battle - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Scervo ~ Dreadfuse Battle - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Scrapper's Theme - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Sealed Grounds - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Sealed Temple - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Sealing The Imprisoned - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Shipyard Minecart Ride - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Sky Keep - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Skyloft - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Skyview Temple - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Staff Roll Credits - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Stalfos ~ Stalmaster Battle - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Stealth (Eldin Volcano) - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Tadtone Hunt - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Temple of Hylia - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Temple Spring - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Tension - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "The Demon King, Demise Battle ~Rising~ - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "The Enchanted Earth Below - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "The Hordes of Darkness - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "The Isle of Songs - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "The Lumpy Pumpkin - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "The Pumpkin Song - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Theme of the Kikwis - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Volcano Summit - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Zelda's Lullaby - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],
    "Zelda's Theme - Skyward Sword": [2011, "Nintendo Wii", "Skyward Sword"],



    // SPIRIT TRACKS
    "Aboda Village - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Anouki Village - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Byrne - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Byrne Awakes - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Byrne Comes to the Rescue - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Cragma, Lava Lord - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Credits - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Cursed Overworld - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Dark Trains Appear - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Dungeon Gauntlet - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Facing The Demon Train - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Fight Against Byrne - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Fighting Cole and Malladus - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Final Battle ~ Malladus - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Final Battle ~ Protecting Zelda - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Fire and Sand Temple - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Fleeing by Demon Train - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Forest, Snow and Ocean Temple - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Fraaz, Master Of Icy Fire - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Goron Village - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Lost Woods - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Mini Boss - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Papuchia Village - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Phytops, Barbed Menace - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Sanctuary - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Stagnox, Armored Colossus - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Tank And Bomb Ship Attack - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "The Dark Realm - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "The Force Gem Awakens - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],
    "Underwater - Spirit Tracks": [2009, "Nintendo DS", "Spirit Tracks"],



    // TEARS OF THE KINGDOM
    "3rd Trailer - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Ancient Zora Waterworks - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Battle: Field (Boss Bokoblin) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Battle: Temple - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Colgera Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Construct Factory - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Demon Dragon Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Demon King Ganondorf Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Demon King Ganondorf Battle (Second Form) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Depths - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Depths Abandoned Mine - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Diving - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Diving (Depths) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Dragonhead Island - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Encounter with Rauru, Source of the Right Arm - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Encounter with Yona - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Field (High Sky) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Fire Temple - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Flux Construct Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Forgotten Foundation: Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Frox Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Gerudo Shelter - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Gerudo Town (During the Phenomenon) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Gleeok Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Gloom Spawn Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Gloom's Lair - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Goron City (During the Phenomenon) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Hateno Ancient Tech Lab - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Hateno School - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Hudson Construction Site (Day) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Hudson Construction Site (Night) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Investigation to the Clouds - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Koltin - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Korok Forest (During the Phenomenon) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Light Dragon - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Lightning Temple - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Lightroot - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Link's House - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Lomei Labyrinth (Depths Labyrinth) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Lomei Labyrinth (Top Floor) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Lookout Landing - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Lookout Landing Shrouded in Dark Clouds - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Lucky Clover Gazette - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Lurelin Village Restoration Feast - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Marbled Gohma Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Mineru, Sage of Spirit - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Mini-Game (Ball Toss) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Mini-Game (Dive Ceremony) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Mini-Game (Mine-Cart Land) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Mini-Game (Yiga Clan Training) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Mipha Court - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Moragia Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Mucktorok Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Oh, Link... I'm Home! - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Opening - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Phantom Ganon Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Prologue (First Half) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Purify the Sludge-Covered Statue - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Queen Gibdo Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Rauru's Guidance - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Reunion with Riju - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Reunion with Sidon - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Reunion with Tulin - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Riju, Sage of Lightning - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Rito Village (During the Phenomenon) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Rocky Area - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Seized Construct Batte - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Serenade to a Great Fairy - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Shrine of Light - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Shrine of Light: Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Shrine of Light: Before the Trial - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Shrine of Light: Blessing - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Sidon, Sage of Water - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Sky Island - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Sludge Like Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Spirit Temple - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Tarrey Town (Night) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Temple of Time - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "The Cece Hat - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "The Demon King's Army - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "The Mayoral Election - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "The Return of Master Kohga: Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "The World-Renowned Cece - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Thunderhead Isles - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "To Her Hand - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Tulin, Sage of Wind - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Tulin's Bow Taken - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Water Temple - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Wind Temple - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Yiga Clan Hideout - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "You Must Find Me - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Yunobo (Clearly Not Himself) Battle - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Yunobo, Sage of Fire - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "YunoboCo HQ - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],
    "Zora's Domain (During the Phenomenon) - Tears of the Kingdom": [2023, "Nintendo Switch", "Tears of the Kingdom"],



    // THE ADVENTURE OF LINK
    "Battle - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Boss - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Dark Link - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Ending - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Great Palace - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Indoors - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Overworld - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Temple - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Title - The Adventure of Link": [1987, "NES", "The Adventure of Link"],
    "Village - The Adventure of Link": [1987, "NES", "The Adventure of Link"],



    // THE LEGEND OF ZELDA
    "Death Mountain - The Legend of Zelda": [1986, "NES", "The Legend of Zelda"],
    "Dungeon - The Legend of Zelda": [1986, "NES", "The Legend of Zelda"],
    "Intro - The Legend of Zelda": [1986, "NES", "The Legend of Zelda"],
    "Overworld - The Legend of Zelda": [1986, "NES", "The Legend of Zelda"],



    // THE MINISH CAP
    "Boss - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Castor Wilds - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Cave - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Cave of Flames - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Cloud Tops - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Elemental Sanctuary - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Fairy Fountain - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "File Select - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Hyrule Castle - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Hyrule Field - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Hyrule Town - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Inside a House - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Into the Skies - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Introduction - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Mini Boss - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Minish Village - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Minish Woods - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Mt. Crenel - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Palace of Winds - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Picori Festival - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Royal Crypt - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Royal Valley - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Temple of Droplets - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "The Minish Cap - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Vaati Attacks - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Vaati Battle - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Vaati's Theme - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Vaati's Wrath - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],
    "Wind Ruins - The Minish Cap": [2004, "Game Boy Advance", "The Minish Cap"],



    // THE WIND WAKER
    "Aryll's Theme - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Battle - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Beedle's Shop - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Departure - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Dragon Roost Island - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Earth Temple - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Farewell Hyrule King - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Forest Haven - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Forsaken Fortress - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Ganon's Castle - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Ganondorf Battle - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Gohdan - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Gohma Battle First Half - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Gohma Battle Second Half - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Grandma's Theme - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Helmaroc King - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Hyrule Castle - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Jabun - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Jalhalla - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Kalle Demos - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Makar's Prayer ~ Wind God's Aria - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Maritime Battle - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Medli's Prayer ~ Earth God's Lyric - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Mini Boss - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Molgera Battle - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Outset Island - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Phantom Ganon - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Pirates - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Potion Shop - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Puppet Ganon - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Puppet Ganon (Snake) - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Puppet Ganon (Spider) - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "The Deku Tree and Koroks - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "The Fairy Queen - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "The Great Sea - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "The Great Sea is Cursed - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "The Legendary Hero - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "The Second Maritime Battle - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Title Theme - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "To Hyrule - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Tower of the Gods - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Wind Temple - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],
    "Windfall Island - The Wind Waker": [2002, "Nintendo GameCube", "The Wind Waker"],



    // THE WIND WAKER HD
    "File Select - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Forsaken Fortress - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Gohma Battle - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Grandma's Theme - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Molgera - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Outset Island - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Pirates - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Puppet Ganon - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Puppet Ganon (Snake) - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Puppet Ganon (Spider) - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],
    "Windfall Island - The Wind Waker HD": [2013, "Wii U", "The Wind Waker HD"],



    // TRI FORCE HEROES
    "Boss - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Coliseum - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Combat - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Combat Results - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Curse - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Daily Riches - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Dark Links Battle - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Den of Trials - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Dunes - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Fortress - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "History of Hytopia - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Hytopia Castle - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Ice Cavern - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "King Tuft - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Lady Maud's Theme - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Lady Maud Battle - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Mini Boss - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Miniboss: Hinox - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Riverside - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Ruins - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Sir Combsly - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Sky Realm - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Sky Temple - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Staff Roll Credits - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Stage Selection - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Tailor - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Title Screen - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Treasure Room - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Village - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],
    "Volcano - Tri Force Heroes": [2015, "Nintendo 3DS", "Tri Force Heroes"],



    // TWILIGHT PRINCESS
    "Aeralfos - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Agitha's Castle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Arbiter's Grounds - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Argorok Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Armogohma Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Beast Ganon Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Beast in the Village - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Blizzeta Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Boss Defeated - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Canon Repair - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Cave - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "City in the Sky - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Courage - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Dangoro Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Darknut Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Death Mountain - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Death Sword - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Diababa - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Enter the Darkness - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Falbi's House - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Faron Woods - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Fishing Hit! - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Forest Temple - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Fyer's Cannon - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Fyrus Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Ganondorf Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Gerudo Desert - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Goron Mines - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Graveyard - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Herd Game - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Hidden Skill Training - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Hidden Village - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Horse Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Horseback Ganondorf Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Hyrule Castle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Hyrule Castle Tower - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Hyrule Castle Town - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Hyrule Field - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Illia's Theme - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Inside a House - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Kakariko is Saved - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Kakariko Village - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "King Bulblin - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Lake Hylia - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Lamentation of the Spirits - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Light and Darkness - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Malo Mart - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Meet Illia - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Midna's Lament - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Midna's Theme - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Morpheel Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Ooccoo's Theme - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Ook - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Opening - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Orchestra Piece #1 - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Orchestra Piece #2 - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Ordon Ranch - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Ordon Village - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Palace of Twilight - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Postman's Theme - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Prince Ralis is Saved - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Puppet Zelda - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Queen Rutela - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Rodeo Game - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Rollgoal - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Sacred Grove - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Sacrifice - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Sanctuary - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Shadow Insect - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Shop - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Sled Game - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Snowpeak - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Snowpeak Ruins - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Spirit's Lament - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Staff Credits - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Stallord Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "STAR Game - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Statue Game - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Sumo Game - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Temple of Time - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "The Demon Thief - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "The Sages - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Title Theme - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Twilight - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Twilight Realm - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Twilit Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Twilit Cargo Game - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Ways of the Sword - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Zant Battle - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Zelda's Theme - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],
    "Zora's Domain - Twilight Princess": [2006, "Nintendo GameCube / Wii", "Twilight Princess"],



    // EXTRA
    "Dale Zelda Dale - Extra": [2024, "YouTube", "Extra"]

});


function createMetadata(mtd) {
    let m = {}
    for(const soundtrack in mtd) {
        m[soundtrack] = {
            'year': mtd[soundtrack][0],
            'device': mtd[soundtrack][1],
            'game': mtd[soundtrack][2]
        }
    }
    return m
}
function _onSubmit() {
}

function appendMetadata(guess, row) {
    if (!guess.isCorrect) {
        let guessMeta = _metadata[guess.answer];
        let heardleMeta = _metadata[currentHeardle.correctAnswer];

        if (guessMeta && heardleMeta) {
            const metaEvaluation = document.createElement("div");
            metaEvaluation.style.maxWidth = "60%";

            metaEvaluation.innerHTML = `
                <div>
                    <div>Year: 
                        <span style="color:${heardleMeta.year == guessMeta.year ? '#2ecc71' : '#e74c3c'}">
                            ${heardleMeta.year > guessMeta.year ? `Newer than ${guessMeta.year}.` : heardleMeta.year == guessMeta.year ? `${guessMeta.year} is correct!` : `Older than ${guessMeta.year}.`}
                        </span>
                    </div>

                    <div>Console: 
                        <span style="color:${heardleMeta.device == guessMeta.device ? '#2ecc71' : '#e74c3c'}">
                            ${heardleMeta.device == guessMeta.device ? `${guessMeta.device} is correct!` : `${guessMeta.device} is incorrect.`}
                        </span>
                    </div>

                    <div>Game: 
                        <span style="color:${heardleMeta.game == guessMeta.game ? '#2ecc71' : '#e74c3c'}">
                            ${heardleMeta.game == guessMeta.game ? `${guessMeta.game} is correct!` : `${guessMeta.game} is incorrect.`}
                        </span>
                    </div>
                </div>
            `;

            row.appendChild(metaEvaluation);
        }
    }
}


function setCurrentHeardle(l) {
    currentHeardle = l;
    setTimeout(() => {
        const rows = document.querySelectorAll("body > main > div.w-full.flex.flex-col.flex-grow.relative > div > div > div");
        stats = localStorage.getItem("userStats")
        if(stats != null ) {
            paresdStats = JSON.parse(stats)
            paresdStats.filter(p => p.correctAnswer == currentHeardle.correctAnswer)[0].guessList.forEach((guess, index) => {
                appendMetadata(guess, rows[index])
            })
        }
    }, 200)
}

function evaluateGuessMetadata(v) {
    const rows = document.querySelectorAll("body > main > div.w-full.flex.flex-col.flex-grow.relative > div > div > div");
    const last = v[v.length-1]
    appendMetadata(last, rows[v.length-1]);
}

let currentHeardle = null;
